<a href="https://colab.research.google.com/github/AfrinHossai/cs171-police-call-forecasting/blob/main/notebooks/01_data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
import os

data_folder = "/content/drive/MyDrive/CS171_Police_Call_Project/data_raw"

print(os.listdir(data_folder))

['police_calls_2024.csv', 'police_calls_2025.csv', 'police_calls_2026.csv']

In [3]:
import pandas as pd
import os

file_paths = {
    "2024": os.path.join(data_folder, "police_calls_2024.csv"),
    "2025": os.path.join(data_folder, "police_calls_2025.csv"),
    "2026": os.path.join(data_folder, "police_calls_2026.csv")
}

datasets = {}

for year, path in file_paths.items():
    datasets[year] = pd.read_csv(path, low_memory=False)

    print(f"\n{'=' * 20} {year} {'=' * 20}")
    print("Rows and columns:", datasets[year].shape)
    print("Column names:")
    print(datasets[year].columns.tolist())

==================== 2024 ====================
Rows and columns: (272506, 16)
Column names:
['CDTS', 'EID', 'START_DATE', 'CALL_NUMBER', 'PRIORITY', 'REPORT_DATE', 'OFFENSE_DATE', 'OFFENSE_TIME', 'CALLTYPE_CODE', 'CALL_TYPE', 'FINAL_DISPO_CODE', 'FINAL_DISPO', 'ADDRESS', 'CITY', 'STATE', 'UNHOUSED']

==================== 2025 ====================
Rows and columns: (262095, 16)
Column names:
['CDTS', 'EID', 'START_DATE', 'CALL_NUMBER', 'PRIORITY', 'REPORT_DATE', 'OFFENSE_DATE', 'OFFENSE_TIME', 'CALLTYPE_CODE', 'CALL_TYPE', 'FINAL_DISPO_CODE', 'FINAL_DISPO', 'ADDRESS', 'CITY', 'STATE', 'UNHOUSED']

==================== 2026 ====================
Rows and columns: (145798, 16)
Column names:
['CDTS', 'EID', 'START_DATE', 'CALL_NUMBER', 'PRIORITY', 'REPORT_DATE', 'OFFENSE_DATE', 'OFFENSE_TIME', 'CALLTYPE_CODE', 'CALL_TYPE', 'FINAL_DISPO_CODE', 'FINAL_DISPO', 'ADDRESS', 'CITY', 'STATE', 'UNHOUSED']

In [4]:
for year, df in datasets.items():
    print(f"\n{'=' * 25} {year} {'=' * 25}")

    print("\nFirst 3 rows:")
    display(df.head(3))

    print("\nColumn data types:")
    print(df.dtypes)

    print("\nMissing values:")
    missing_values = df.isna().sum()
    print(missing_values[missing_values > 0].sort_values(ascending=False))

    print("\nExact duplicate rows:")
    print(df.duplicated().sum())

========================= 2024 =========================

First 3 rows:

,CDTS,EID,START_DATE,CALL_NUMBER,PRIORITY,REPORT_DATE,OFFENSE_DATE,OFFENSE_TIME,CALLTYPE_CODE,CALL_TYPE,FINAL_DISPO_CODE,FINAL_DISPO,ADDRESS,CITY,STATE,UNHOUSED
0,20240210012507PS,9894114,3/4/2026,P240410001,2,2/10/2024,2/10/2024,0:01:35,23103,RECKLESS DRIVING,N,No report required; dispatch record only,NaN,San Jose,CA,NaN
1,20240210000846PS,9894116,3/4/2026,P240410002,4,2/10/2024,2/10/2024,0:02:24,415FC,"DISTURBANCE, FIRECRACKERS",DUPNCAN,No Disposition,LUCRETIA AV & TAJI DR,San Jose,CA,NaN
2,20240210000737PS,9894118,3/4/2026,P240410003,4,2/10/2024,2/10/2024,0:03:13,415FC,"DISTURBANCE, FIRECRACKERS",CAN,Canceled,NICKEL AV & S KING RD,San Jose,CA,NaN

Column data types:
CDTS                object
EID                  int64
START_DATE          object
CALL_NUMBER         object
PRIORITY             int64
REPORT_DATE         object
OFFENSE_DATE        object
OFFENSE_TIME        object
CALLTYPE_CODE       object
CALL_TYPE           object
FINAL_DISPO_CODE    object
FINAL_DISPO         object
ADDRESS             object
CITY                object
STATE               object
UNHOUSED            object
dtype: object

Missing values:
UNHOUSED    257926
ADDRESS       7445
dtype: int64

Exact duplicate rows:
0

========================= 2025 =========================

First 3 rows:

,CDTS,EID,START_DATE,CALL_NUMBER,PRIORITY,REPORT_DATE,OFFENSE_DATE,OFFENSE_TIME,CALLTYPE_CODE,CALL_TYPE,FINAL_DISPO_CODE,FINAL_DISPO,ADDRESS,CITY,STATE,UNHOUSED
0,20250102011009PS,10305815,3/4/2026,P250010001,3,2025-01-01,2025-01-01,00:00:02,602PC,TRESPASSING,N,No report required; dispatch record only,test,San Jose,CA,NaN
1,20250101000744PS,10305820,3/4/2026,P250010006,2,2025-01-01,2025-01-01,00:02:34,1057,FIREARMS DISCHARGED,CAN,Canceled,[1700]-[1800] OLIVETREE DR,San Jose,CA,NaN
2,20250101001204PS,10305823,3/4/2026,P250010007,4,2025-01-01,2025-01-01,00:03:38,415FC,"DISTURBANCE, FIRECRACKERS",CAN,Canceled,MALABAR DR & WESTBORO DR,San Jose,CA,NaN

Column data types:
CDTS                object
EID                  int64
START_DATE          object
CALL_NUMBER         object
PRIORITY             int64
REPORT_DATE         object
OFFENSE_DATE        object
OFFENSE_TIME        object
CALLTYPE_CODE       object
CALL_TYPE           object
FINAL_DISPO_CODE    object
FINAL_DISPO         object
ADDRESS             object
CITY                object
STATE               object
UNHOUSED            object
dtype: object

Missing values:
UNHOUSED    248172
ADDRESS       7539
dtype: int64

Exact duplicate rows:
0

========================= 2026 =========================

First 3 rows:

,CDTS,EID,START_DATE,CALL_NUMBER,PRIORITY,REPORT_DATE,OFFENSE_DATE,OFFENSE_TIME,CALLTYPE_CODE,CALL_TYPE,FINAL_DISPO_CODE,FINAL_DISPO,ADDRESS,CITY,STATE,UNHOUSED
0,20260101042824PS,10756273,3/25/2026 12:00:00 AM,P260010002,3,1/1/2026 12:00:00 AM,1/1/2026 12:00:00 AM,00:04:56,1033A,"ALARM, AUDIBLE",U,Unfounded event,[300]-[400] E SANTA CLARA ST,San Jose,CA,NaN
1,20260101003226PS,10756274,3/25/2026 12:00:00 AM,P260010003,1,1/1/2026 12:00:00 AM,1/1/2026 12:00:00 AM,00:05:28,246,SHOOTING INTO OCCP VEH OR DWELLING,R,Report taken,[200]-[300] S 22ND ST,San Jose,CA,NaN
2,20260101000639PS,10756275,3/25/2026 12:00:00 AM,P260010004,4,1/1/2026 12:00:00 AM,1/1/2026 12:00:00 AM,00:05:32,415FC,"DISTURBANCE, FIRECRACKERS",CAN,Canceled,W HEDDING ST & DANA AV,San Jose,CA,NaN

Column data types:
CDTS                object
EID                  int64
START_DATE          object
CALL_NUMBER         object
PRIORITY             int64
REPORT_DATE         object
OFFENSE_DATE        object
OFFENSE_TIME        object
CALLTYPE_CODE       object
CALL_TYPE           object
FINAL_DISPO_CODE    object
FINAL_DISPO         object
ADDRESS             object
CITY                object
STATE               object
UNHOUSED            object
dtype: object

Missing values:
UNHOUSED    139148
ADDRESS       4025
dtype: int64

Exact duplicate rows:
8020

In [5]:
df_2026 = datasets["2026"]

# Mark every row belonging to an exact-duplicate group
duplicate_mask = df_2026.duplicated(keep=False)
duplicate_rows = df_2026.loc[duplicate_mask].copy()

print("Total 2026 rows:", len(df_2026))
print("Rows belonging to duplicate groups:", duplicate_mask.sum())
print("Extra duplicate copies:", df_2026.duplicated().sum())
print(
    "Unique records represented by duplicate groups:",
    duplicate_rows.drop_duplicates().shape[0]
)

print("\nFirst 20 duplicated rows:")
display(
    duplicate_rows
    .sort_values(["CALL_NUMBER", "EID", "CDTS"])
    .head(20)
)

print("\nLargest duplicate groups by CALL_NUMBER:")
print(
    duplicate_rows
    .groupby("CALL_NUMBER", dropna=False)
    .size()
    .sort_values(ascending=False)
    .head(15)
)

Total 2026 rows: 145798
Rows belonging to duplicate groups: 12946
Extra duplicate copies: 8020
Unique records represented by duplicate groups: 4926

First 20 duplicated rows:

,CDTS,EID,START_DATE,CALL_NUMBER,PRIORITY,REPORT_DATE,OFFENSE_DATE,OFFENSE_TIME,CALLTYPE_CODE,CALL_TYPE,FINAL_DISPO_CODE,FINAL_DISPO,ADDRESS,CITY,STATE,UNHOUSED
62326,20260328000528PD,10859566,4/5/2026 12:00:00 AM,P260870001,6,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:00:44,1195,VEHICLE STOP,N,No report required; dispatch record only,BLOSSOM HILL RD & RUSSO DR,San Jose,CA,NaN
66591,20260328000528PD,10859566,4/5/2026 12:00:00 AM,P260870001,6,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:00:44,1195,VEHICLE STOP,N,No report required; dispatch record only,BLOSSOM HILL RD & RUSSO DR,San Jose,CA,NaN
62327,20260328004815PD,10859567,4/5/2026 12:00:00 AM,P260870002,2,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:01:31,415,DISTURBANCE,G,Gone on Arrival/unable to locate,ZANKER RD & BAYPOINTE PY,San Jose,CA,NaN
66592,20260328004815PD,10859567,4/5/2026 12:00:00 AM,P260870002,2,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:01:31,415,DISTURBANCE,G,Gone on Arrival/unable to locate,ZANKER RD & BAYPOINTE PY,San Jose,CA,NaN
62328,20260328001309PD,10859568,4/5/2026 12:00:00 AM,P260870003,2,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:03:47,1066,SUSPICIOUS PERSON,CAN,Canceled,MCLAUGHLIN AV & MIDPINE AV,San Jose,CA,NaN
66593,20260328001309PD,10859568,4/5/2026 12:00:00 AM,P260870003,2,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:03:47,1066,SUSPICIOUS PERSON,CAN,Canceled,MCLAUGHLIN AV & MIDPINE AV,San Jose,CA,NaN
62329,20260328022926PD,10859569,4/5/2026 12:00:00 AM,P260870004,3,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:04:30,WELCK,WELFARE CHECK,N,No report required; dispatch record only,[200]-[300] HOSPITAL PY,San Jose,CA,NaN
66594,20260328022926PD,10859569,4/5/2026 12:00:00 AM,P260870004,3,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:04:30,WELCK,WELFARE CHECK,N,No report required; dispatch record only,[200]-[300] HOSPITAL PY,San Jose,CA,NaN
62330,20260328002315PD,10859570,4/5/2026 12:00:00 AM,P260870005,6,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:07:55,1195,VEHICLE STOP,N,No report required; dispatch record only,E WILLIAM ST & S 8TH ST,San Jose,CA,NaN
66595,20260328002315PD,10859570,4/5/2026 12:00:00 AM,P260870005,6,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:07:55,1195,VEHICLE STOP,N,No report required; dispatch record only,E WILLIAM ST & S 8TH ST,San Jose,CA,NaN
62332,20260328002137PD,10859572,4/5/2026 12:00:00 AM,P260870007,6,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:09:55,1195,VEHICLE STOP,N,No report required; dispatch record only,S 3RD ST & E SAN FERNANDO ST,San Jose,CA,NaN
66597,20260328002137PD,10859572,4/5/2026 12:00:00 AM,P260870007,6,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:09:55,1195,VEHICLE STOP,N,No report required; dispatch record only,S 3RD ST & E SAN FERNANDO ST,San Jose,CA,NaN
62333,20260328005443PD,10859574,4/5/2026 12:00:00 AM,P260870009,3,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:13:05,1066,SUSPICIOUS PERSON,N,No report required; dispatch record only,[2000]-[2100] TERILYN AV,San Jose,CA,NaN
66598,20260328005443PD,10859574,4/5/2026 12:00:00 AM,P260870009,3,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:13:05,1066,SUSPICIOUS PERSON,N,No report required; dispatch record only,[2000]-[2100] TERILYN AV,San Jose,CA,NaN
62334,20260328005953PD,10859578,4/5/2026 12:00:00 AM,P260870010,3,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:17:00,1033A,"ALARM, AUDIBLE",N,No report required; dispatch record only,[1000]-[1100] WILLOW ST,San Jose,CA,NaN
66599,20260328005953PD,10859578,4/5/2026 12:00:00 AM,P260870010,3,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:17:00,1033A,"ALARM, AUDIBLE",N,No report required; dispatch record only,[1000]-[1100] WILLOW ST,San Jose,CA,NaN
62335,20260328003939PD,10859579,4/5/2026 12:00:00 AM,P260870011,3,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:18:16,1033A,"ALARM, AUDIBLE",N,No report required; dispatch record only,[400]-[500] MADERA AV,San Jose,CA,NaN
66600,20260328003939PD,10859579,4/5/2026 12:00:00 AM,P260870011,3,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:18:16,1033A,"ALARM, AUDIBLE",N,No report required; dispatch record only,[400]-[500] MADERA AV,San Jose,CA,NaN
62336,20260328011910PD,10859581,4/5/2026 12:00:00 AM,P260870013,3,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:24:23,602PC,TRESPASSING,G,Gone on Arrival/unable to locate,[2100]-[2200] MORRILL AV,San Jose,CA,NaN
66601,20260328011910PD,10859581,4/5/2026 12:00:00 AM,P260870013,3,3/28/2026 12:00:00 AM,3/28/2026 12:00:00 AM,00:24:23,602PC,TRESPASSING,G,Gone on Arrival/unable to locate,[2100]-[2200] MORRILL AV,San Jose,CA,NaN

Largest duplicate groups by CALL_NUMBER:
CALL_NUMBER
P260920949    3
P260920948    3
P260920947    3
P260920946    3
P260920944    3
P260920943    3
P260920942    3
P260920940    3
P260920939    3
P260920938    3
P260920937    3
P260920935    3
P260920934    3
P260920932    3
P260920931    3
dtype: int64

In [6]:
cleaned_datasets = {}
duplicate_audit = []

for year, df in datasets.items():
    before_rows = len(df)

    cleaned_df = df.drop_duplicates().reset_index(drop=True)

    after_rows = len(cleaned_df)
    removed_rows = before_rows - after_rows

    cleaned_datasets[year] = cleaned_df

    duplicate_audit.append({
        "year": year,
        "rows_before": before_rows,
        "duplicates_removed": removed_rows,
        "rows_after": after_rows
    })

duplicate_audit_df = pd.DataFrame(duplicate_audit)

display(duplicate_audit_df)

print("\nRemaining exact duplicates:")
for year, df in cleaned_datasets.items():
    print(year, df.duplicated().sum())

   year  rows_before  duplicates_removed  rows_after
0  2024       272506                   0      272506
1  2025       262095                   0      262095
2  2026       145798                8020      137778

Remaining exact duplicates:
2024 0
2025 0
2026 0

In [7]:
timestamp_audit = []

for year, df in cleaned_datasets.items():
    df = df.copy()

    # Parse the date and time columns
    parsed_date = pd.to_datetime(
        df["OFFENSE_DATE"],
        errors="coerce",
        format="mixed"
    )

    parsed_time = pd.to_timedelta(
        df["OFFENSE_TIME"].astype(str),
        errors="coerce"
    )

    # Combine date and time into one timestamp
    df["CALL_DATETIME"] = parsed_date.dt.normalize() + parsed_time

    cleaned_datasets[year] = df

    valid_timestamp = df["CALL_DATETIME"].notna()

    timestamp_audit.append({
        "year": year,
        "total_rows": len(df),
        "invalid_dates": parsed_date.isna().sum(),
        "invalid_times": parsed_time.isna().sum(),
        "invalid_timestamps": df["CALL_DATETIME"].isna().sum(),
        "minimum_timestamp": df["CALL_DATETIME"].min(),
        "maximum_timestamp": df["CALL_DATETIME"].max(),
        "timestamps_outside_expected_year": (
            df.loc[valid_timestamp, "CALL_DATETIME"].dt.year != int(year)
        ).sum()
    })

timestamp_audit_df = pd.DataFrame(timestamp_audit)

display(timestamp_audit_df)

print("\nSample timestamps:")
for year, df in cleaned_datasets.items():
    print(f"\n{year}")
    display(
        df[
            ["OFFENSE_DATE", "OFFENSE_TIME", "CALL_DATETIME"]
        ].head(5)
    )

,year,total_rows,invalid_dates,invalid_times,invalid_timestamps,minimum_timestamp,maximum_timestamp,timestamps_outside_expected_year
0,2024,272506,0,0,0,2024-01-01 00:00:00,2024-12-31 23:59:20,0
1,2025,262095,0,0,0,2025-01-01 00:00:02,2025-12-31 23:57:51,0
2,2026,137778,0,0,0,2026-01-01 00:04:56,2026-07-08 23:55:55,0

Sample timestamps:

2024

  OFFENSE_DATE OFFENSE_TIME       CALL_DATETIME
0    2/10/2024      0:01:35 2024-02-10 00:01:35
1    2/10/2024      0:02:24 2024-02-10 00:02:24
2    2/10/2024      0:03:13 2024-02-10 00:03:13
3    2/10/2024      0:04:02 2024-02-10 00:04:02
4    2/10/2024      0:04:34 2024-02-10 00:04:34

2025

  OFFENSE_DATE OFFENSE_TIME       CALL_DATETIME
0   2025-01-01     00:00:02 2025-01-01 00:00:02
1   2025-01-01     00:02:34 2025-01-01 00:02:34
2   2025-01-01     00:03:38 2025-01-01 00:03:38
3   2025-01-01     00:04:08 2025-01-01 00:04:08
4   2025-01-01     00:04:36 2025-01-01 00:04:36

2026

           OFFENSE_DATE OFFENSE_TIME       CALL_DATETIME
0  1/1/2026 12:00:00 AM     00:04:56 2026-01-01 00:04:56
1  1/1/2026 12:00:00 AM     00:05:28 2026-01-01 00:05:28
2  1/1/2026 12:00:00 AM     00:05:32 2026-01-01 00:05:32
3  1/1/2026 12:00:00 AM     00:05:42 2026-01-01 00:05:42
4  1/1/2026 12:00:00 AM     00:06:53 2026-01-01 00:06:53

In [8]:
combined_parts = []

for year, df in cleaned_datasets.items():
    yearly_df = df.copy()
    yearly_df["SOURCE_YEAR"] = int(year)
    combined_parts.append(yearly_df)

combined_df = pd.concat(
    combined_parts,
    ignore_index=True
)

combined_df = (
    combined_df
    .sort_values("CALL_DATETIME")
    .reset_index(drop=True)
)

print("Combined shape:", combined_df.shape)
print("Expected rows:", sum(len(df) for df in cleaned_datasets.values()))
print("Actual rows:", len(combined_df))

print("\nRows by source year:")
print(
    combined_df["SOURCE_YEAR"]
    .value_counts()
    .sort_index()
)

print("\nTimestamp range:")
print("Minimum:", combined_df["CALL_DATETIME"].min())
print("Maximum:", combined_df["CALL_DATETIME"].max())

print("\nValidation checks:")
print(
    "Chronologically sorted:",
    combined_df["CALL_DATETIME"].is_monotonic_increasing
)
print(
    "Missing timestamps:",
    combined_df["CALL_DATETIME"].isna().sum()
)
print(
    "Year mismatches:",
    (
        combined_df["CALL_DATETIME"].dt.year
        != combined_df["SOURCE_YEAR"]
    ).sum()
)
print(
    "Exact duplicates after combination:",
    combined_df.duplicated().sum()
)

print("\nFirst 3 combined rows:")
display(combined_df.head(3))

print("\nLast 3 combined rows:")
display(combined_df.tail(3))

Combined shape: (672379, 18)
Expected rows: 672379
Actual rows: 672379

Rows by source year:
SOURCE_YEAR
2024    272506
2025    262095
2026    137778
Name: count, dtype: int64

Timestamp range:
Minimum: 2024-01-01 00:00:00
Maximum: 2026-07-08 23:55:55

Validation checks:
Chronologically sorted: True
Missing timestamps: 0
Year mismatches: 0
Exact duplicates after combination: 0

First 3 combined rows:

,CDTS,EID,START_DATE,CALL_NUMBER,PRIORITY,REPORT_DATE,OFFENSE_DATE,OFFENSE_TIME,CALLTYPE_CODE,CALL_TYPE,FINAL_DISPO_CODE,FINAL_DISPO,ADDRESS,CITY,STATE,UNHOUSED,CALL_DATETIME,SOURCE_YEAR
0,20240101000257PS,9844603,3/23/2026,P240010001,3,1/1/2024,1/1/2024,0:00:00,1033A,"ALARM, AUDIBLE",CAN,Canceled,[0]-[100] E SANTA CLARA ST,San Jose,CA,NaN,2024-01-01 00:00:00,2024
1,20240101004031PS,9844604,3/23/2026,P240010002,3,1/1/2024,1/1/2024,0:00:43,415M,"DISTURBANCE, MUSIC",CAN,Canceled,[6500]-[6600] STONEHILL DR,San Jose,CA,NaN,2024-01-01 00:00:43,2024
2,20240101002736PS,9844605,3/23/2026,P240010003,3,1/1/2024,1/1/2024,0:00:49,SUSCIR,SUSPICIOUS CIRCUMSTANCES,CAN,Canceled,[5700]-[5800] WALTRIP LN,San Jose,CA,NaN,2024-01-01 00:00:49,2024

Last 3 combined rows:

,CDTS,EID,START_DATE,CALL_NUMBER,PRIORITY,REPORT_DATE,OFFENSE_DATE,OFFENSE_TIME,CALLTYPE_CODE,CALL_TYPE,FINAL_DISPO_CODE,FINAL_DISPO,ADDRESS,CITY,STATE,UNHOUSED,CALL_DATETIME,SOURCE_YEAR
672376,20260709004731PD,10986212,7/8/2026 12:00:00 AM,P261890864,2,7/8/2026 12:00:00 AM,7/8/2026 12:00:00 AM,23:55:21,415,DISTURBANCE,N,No report required; dispatch record only,[2900]-[3000] UNION AV,San Jose,CA,NaN,2026-07-08 23:55:21,2026
672377,20260709002851PD,10986213,7/8/2026 12:00:00 AM,P261890865,6,7/8/2026 12:00:00 AM,7/8/2026 12:00:00 AM,23:55:42,1195,VEHICLE STOP,N,No report required; dispatch record only,NaN,San Jose,CA,NaN,2026-07-08 23:55:42,2026
672378,20260708235652PD,10986215,7/8/2026 12:00:00 AM,P261890867,4,7/8/2026 12:00:00 AM,7/8/2026 12:00:00 AM,23:55:55,1062,MEET THE CITIZEN,DUPNCAN,No Disposition,NaN,San Jose,CA,NaN,2026-07-08 23:55:55,2026

In [9]:
# Assign every incident to its corresponding hourly interval
combined_df["HOUR"] = combined_df["CALL_DATETIME"].dt.floor("h")

# Count incidents in each observed hour
observed_hourly_counts = (
    combined_df
    .groupby("HOUR")
    .size()
    .rename("TOTAL_CALLS")
)

# Create a complete hourly timeline
complete_hour_index = pd.date_range(
    start=combined_df["HOUR"].min(),
    end=combined_df["HOUR"].max(),
    freq="h"
)

# Insert any missing hours with zero calls
hourly_df = (
    observed_hourly_counts
    .reindex(complete_hour_index, fill_value=0)
    .rename_axis("HOUR")
    .reset_index()
)

print("Incident rows in combined data:", len(combined_df))
print("Calls represented in hourly data:", hourly_df["TOTAL_CALLS"].sum())
print("Observed hourly intervals:", len(observed_hourly_counts))
print("Complete hourly intervals:", len(hourly_df))
print(
    "Hours inserted with zero calls:",
    (hourly_df["TOTAL_CALLS"] == 0).sum()
)

print("\nHourly timestamp range:")
print("Minimum:", hourly_df["HOUR"].min())
print("Maximum:", hourly_df["HOUR"].max())

print("\nHourly call-count summary:")
display(hourly_df["TOTAL_CALLS"].describe().to_frame())

print("\nFirst 10 hourly rows:")
display(hourly_df.head(10))

print("\nLast 10 hourly rows:")
display(hourly_df.tail(10))

Incident rows in combined data: 672379
Calls represented in hourly data: 672379
Observed hourly intervals: 22076
Complete hourly intervals: 22080
Hours inserted with zero calls: 4

Hourly timestamp range:
Minimum: 2024-01-01 00:00:00
Maximum: 2026-07-08 23:00:00

Hourly call-count summary:

        TOTAL_CALLS
count  22080.000000
mean      30.451947
std       12.443816
min        0.000000
25%       22.000000
50%       31.000000
75%       38.000000
max      166.000000

First 10 hourly rows:

                 HOUR  TOTAL_CALLS
0 2024-01-01 00:00:00           78
1 2024-01-01 01:00:00           68
2 2024-01-01 02:00:00           41
3 2024-01-01 03:00:00           35
4 2024-01-01 04:00:00           32
5 2024-01-01 05:00:00           20
6 2024-01-01 06:00:00           19
7 2024-01-01 07:00:00           16
8 2024-01-01 08:00:00           17
9 2024-01-01 09:00:00           21

Last 10 hourly rows:

                     HOUR  TOTAL_CALLS
22070 2026-07-08 14:00:00           30
22071 2026-07-08 15:00:00           26
22072 2026-07-08 16:00:00           34
22073 2026-07-08 17:00:00           37
22074 2026-07-08 18:00:00           41
22075 2026-07-08 19:00:00           27
22076 2026-07-08 20:00:00           35
22077 2026-07-08 21:00:00           24
22078 2026-07-08 22:00:00           45
22079 2026-07-08 23:00:00           31

In [10]:
zero_hours = hourly_df.loc[
    hourly_df["TOTAL_CALLS"] == 0,
    "HOUR"
].tolist()

print("Number of zero-call hours:", len(zero_hours))
print("\nZero-call timestamps:")

for zero_hour in zero_hours:
    print(zero_hour)

print("\nSurrounding hourly counts:")

for zero_hour in zero_hours:
    print(f"\n{'=' * 60}")
    print("Zero-call hour:", zero_hour)

    surrounding_hours = hourly_df.loc[
        hourly_df["HOUR"].between(
            zero_hour - pd.Timedelta(hours=3),
            zero_hour + pd.Timedelta(hours=3)
        )
    ]

    display(surrounding_hours)

    incident_count = (
        combined_df["HOUR"] == zero_hour
    ).sum()

    print(
        "Incident-level records during this hour:",
        incident_count
    )

Number of zero-call hours: 4

Zero-call timestamps:
2024-03-10 02:00:00
2025-03-09 02:00:00
2026-03-08 02:00:00
2026-03-17 04:00:00

Surrounding hourly counts:

============================================================
Zero-call hour: 2024-03-10 02:00:00

                    HOUR  TOTAL_CALLS
1655 2024-03-09 23:00:00           52
1656 2024-03-10 00:00:00           51
1657 2024-03-10 01:00:00           55
1658 2024-03-10 02:00:00            0
1659 2024-03-10 03:00:00           35
1660 2024-03-10 04:00:00           28
1661 2024-03-10 05:00:00           26

Incident-level records during this hour: 0

============================================================
Zero-call hour: 2025-03-09 02:00:00

                     HOUR  TOTAL_CALLS
10391 2025-03-08 23:00:00           59
10392 2025-03-09 00:00:00           50
10393 2025-03-09 01:00:00           60
10394 2025-03-09 02:00:00            0
10395 2025-03-09 03:00:00           33
10396 2025-03-09 04:00:00           25
10397 2025-03-09 05:00:00           19

Incident-level records during this hour: 0

============================================================
Zero-call hour: 2026-03-08 02:00:00

                     HOUR  TOTAL_CALLS
19127 2026-03-07 23:00:00           61
19128 2026-03-08 00:00:00           35
19129 2026-03-08 01:00:00           40
19130 2026-03-08 02:00:00            0
19131 2026-03-08 03:00:00           38
19132 2026-03-08 04:00:00           18
19133 2026-03-08 05:00:00           19

Incident-level records during this hour: 0

============================================================
Zero-call hour: 2026-03-17 04:00:00

                     HOUR  TOTAL_CALLS
19345 2026-03-17 01:00:00           17
19346 2026-03-17 02:00:00           21
19347 2026-03-17 03:00:00           13
19348 2026-03-17 04:00:00            0
19349 2026-03-17 05:00:00            7
19350 2026-03-17 06:00:00           14
19351 2026-03-17 07:00:00           20

Incident-level records during this hour: 0

In [11]:
unusual_zero_hour = pd.Timestamp("2026-03-17 04:00:00")

print("Hourly counts around the unusual zero hour:")
display(
    hourly_df.loc[
        hourly_df["HOUR"].between(
            unusual_zero_hour - pd.Timedelta(hours=6),
            unusual_zero_hour + pd.Timedelta(hours=6)
        )
    ]
)

print("\nIncident timestamps immediately before the gap:")
display(
    combined_df.loc[
        combined_df["CALL_DATETIME"] < unusual_zero_hour,
        ["CALL_DATETIME", "CALL_NUMBER", "CALL_TYPE", "PRIORITY"]
    ].tail(10)
)

print("\nIncident timestamps immediately after the gap:")
display(
    combined_df.loc[
        combined_df["CALL_DATETIME"] >= unusual_zero_hour
        + pd.Timedelta(hours=1),
        ["CALL_DATETIME", "CALL_NUMBER", "CALL_TYPE", "PRIORITY"]
    ].head(10)
)

print("\nCounts for 4:00 a.m. on nearby dates:")
nearby_4am = hourly_df.loc[
    (hourly_df["HOUR"].dt.hour == 4)
    & hourly_df["HOUR"].between(
        unusual_zero_hour - pd.Timedelta(days=7),
        unusual_zero_hour + pd.Timedelta(days=7)
    )
]

display(nearby_4am)

Hourly counts around the unusual zero hour:

                     HOUR  TOTAL_CALLS
19342 2026-03-16 22:00:00           44
19343 2026-03-16 23:00:00           33
19344 2026-03-17 00:00:00           29
19345 2026-03-17 01:00:00           17
19346 2026-03-17 02:00:00           21
19347 2026-03-17 03:00:00           13
19348 2026-03-17 04:00:00            0
19349 2026-03-17 05:00:00            7
19350 2026-03-17 06:00:00           14
19351 2026-03-17 07:00:00           20
19352 2026-03-17 08:00:00           29
19353 2026-03-17 09:00:00           40
19354 2026-03-17 10:00:00           40

Incident timestamps immediately before the gap:

,CALL_DATETIME,CALL_NUMBER,CALL_TYPE,PRIORITY
585231,2026-03-17 03:07:45,P260760081,"ALARM, AUDIBLE",3
585232,2026-03-17 03:18:08,P260760082,UNK TYPE 911 CALL,2
585233,2026-03-17 03:26:37,P260760083,THEFT,3
585234,2026-03-17 03:28:30,P260760084,VEHICLE STOP,6
585235,2026-03-17 03:33:10,P260760085,"ALARM, AUDIBLE",3
585236,2026-03-17 03:38:19,P260760086,VEHICLE BURGLARY,3
585237,2026-03-17 03:45:01,P260760087,"ALARM, AUDIBLE",3
585238,2026-03-17 03:45:31,P260760088,PROWLER,2
585239,2026-03-17 03:50:16,P260760089,FIRE DEPARTMENT REQUEST FOR PD,2
585240,2026-03-17 03:59:32,P260760091,VEHICLE BURGLARY,2

Incident timestamps immediately after the gap:

,CALL_DATETIME,CALL_NUMBER,CALL_TYPE,PRIORITY
585241,2026-03-17 05:39:09,P260760350,TAMPERING WITH A VEHICLE,3
585242,2026-03-17 05:45:35,P260760353,"ALARM, AUDIBLE",3
585243,2026-03-17 05:47:49,P260760354,STOLEN VEHICLE,3
585244,2026-03-17 05:48:00,P260760355,TAMPERING WITH A VEHICLE,3
585245,2026-03-17 05:48:36,P260760356,DISTURBANCE,2
585246,2026-03-17 05:51:13,P260760357,FIRE DEPARTMENT REQUEST FOR PD,2
585247,2026-03-17 05:56:33,P260760359,"ALARM, SILENT",3
585248,2026-03-17 06:00:16,P260760360,VEHICLE BURGLARY,3
585249,2026-03-17 06:04:24,P260760361,SUSPICIOUS PERSON,3
585250,2026-03-17 06:06:51,P260760364,PARKING VIOLATION,4

Counts for 4:00 a.m. on nearby dates:

                     HOUR  TOTAL_CALLS
19180 2026-03-10 04:00:00           15
19204 2026-03-11 04:00:00            8
19228 2026-03-12 04:00:00           16
19252 2026-03-13 04:00:00            7
19276 2026-03-14 04:00:00           13
19300 2026-03-15 04:00:00           16
19324 2026-03-16 04:00:00            8
19348 2026-03-17 04:00:00            0
19372 2026-03-18 04:00:00           11
19396 2026-03-19 04:00:00           11
19420 2026-03-20 04:00:00           11
19444 2026-03-21 04:00:00           11
19468 2026-03-22 04:00:00           18
19492 2026-03-23 04:00:00           11
19516 2026-03-24 04:00:00           10

In [12]:
# Preserve the original hourly_df
hourly_corrected_df = hourly_df.copy()

dst_nonexistent_hours = pd.to_datetime([
    "2024-03-10 02:00:00",
    "2025-03-09 02:00:00",
    "2026-03-08 02:00:00"
])

suspected_missing_hour = pd.Timestamp("2026-03-17 04:00:00")

# Remove hours that did not exist because of daylight-saving time
hourly_corrected_df = hourly_corrected_df.loc[
    ~hourly_corrected_df["HOUR"].isin(dst_nonexistent_hours)
].copy()

# Mark the suspected data gap as missing, not as zero calls
hourly_corrected_df["MISSING_DATA_FLAG"] = 0

missing_mask = (
    hourly_corrected_df["HOUR"] == suspected_missing_hour
)

hourly_corrected_df.loc[
    missing_mask,
    "TOTAL_CALLS"
] = pd.NA

hourly_corrected_df.loc[
    missing_mask,
    "MISSING_DATA_FLAG"
] = 1

hourly_corrected_df["TOTAL_CALLS"] = (
    hourly_corrected_df["TOTAL_CALLS"]
    .astype("Int64")
)

hourly_corrected_df = (
    hourly_corrected_df
    .reset_index(drop=True)
)

print("Original hourly rows:", len(hourly_df))
print("Corrected hourly rows:", len(hourly_corrected_df))
print(
    "Remaining zero-call hours:",
    (hourly_corrected_df["TOTAL_CALLS"] == 0).sum()
)
print(
    "Missing hourly values:",
    hourly_corrected_df["TOTAL_CALLS"].isna().sum()
)
print(
    "Calls preserved:",
    hourly_corrected_df["TOTAL_CALLS"].sum()
)

print("\nSuspected missing-data row:")
display(
    hourly_corrected_df.loc[
        hourly_corrected_df["MISSING_DATA_FLAG"] == 1
    ]
)

Original hourly rows: 22080
Corrected hourly rows: 22077
Remaining zero-call hours: 0
Missing hourly values: 1
Calls preserved: 672379

Suspected missing-data row:

                     HOUR  TOTAL_CALLS  MISSING_DATA_FLAG
19345 2026-03-17 04:00:00         <NA>                  1

In [13]:
modeling_df = hourly_corrected_df.copy()

# Target: number of calls in the following hourly row
modeling_df["NEXT_HOUR_CALLS"] = (
    modeling_df["TOTAL_CALLS"].shift(-1)
)

# Confirm that the next row represents the expected next clock hour
modeling_df["NEXT_TIMESTAMP"] = (
    modeling_df["HOUR"].shift(-1)
)

modeling_df["HOURS_TO_NEXT"] = (
    modeling_df["NEXT_TIMESTAMP"] - modeling_df["HOUR"]
).dt.total_seconds() / 3600

print("Total rows:", len(modeling_df))
print(
    "Missing current-hour call counts:",
    modeling_df["TOTAL_CALLS"].isna().sum()
)
print(
    "Missing target values:",
    modeling_df["NEXT_HOUR_CALLS"].isna().sum()
)

print("\nTime differences between consecutive rows:")
print(
    modeling_df["HOURS_TO_NEXT"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nRows with missing current or target values:")
display(
    modeling_df.loc[
        modeling_df["TOTAL_CALLS"].isna()
        | modeling_df["NEXT_HOUR_CALLS"].isna(),
        [
            "HOUR",
            "TOTAL_CALLS",
            "NEXT_TIMESTAMP",
            "NEXT_HOUR_CALLS",
            "MISSING_DATA_FLAG",
            "HOURS_TO_NEXT"
        ]
    ]
)

print("\nFirst five target examples:")
display(
    modeling_df[
        ["HOUR", "TOTAL_CALLS", "NEXT_TIMESTAMP", "NEXT_HOUR_CALLS"]
    ].head()
)

Total rows: 22077
Missing current-hour call counts: 1
Missing target values: 2

Time differences between consecutive rows:
HOURS_TO_NEXT
1.0    22073
2.0        3
NaN        1
Name: count, dtype: int64

Rows with missing current or target values:

,HOUR,TOTAL_CALLS,NEXT_TIMESTAMP,NEXT_HOUR_CALLS,MISSING_DATA_FLAG,HOURS_TO_NEXT
19344,2026-03-17 03:00:00,13,2026-03-17 04:00:00,<NA>,0,1.0
19345,2026-03-17 04:00:00,<NA>,2026-03-17 05:00:00,7,1,1.0
22076,2026-07-08 23:00:00,31,NaT,<NA>,0,NaN

First five target examples:

                 HOUR  TOTAL_CALLS      NEXT_TIMESTAMP  NEXT_HOUR_CALLS
0 2024-01-01 00:00:00           78 2024-01-01 01:00:00               68
1 2024-01-01 01:00:00           68 2024-01-01 02:00:00               41
2 2024-01-01 02:00:00           41 2024-01-01 03:00:00               35
3 2024-01-01 03:00:00           35 2024-01-01 04:00:00               32
4 2024-01-01 04:00:00           32 2024-01-01 05:00:00               20

In [14]:
invalid_modeling_rows = modeling_df.loc[
    modeling_df["TOTAL_CALLS"].isna()
    | modeling_df["NEXT_HOUR_CALLS"].isna()
    | (modeling_df["HOURS_TO_NEXT"] != 1)
].copy()

print("Rows excluded from modeling:", len(invalid_modeling_rows))

display(
    invalid_modeling_rows[
        [
            "HOUR",
            "TOTAL_CALLS",
            "NEXT_TIMESTAMP",
            "NEXT_HOUR_CALLS",
            "MISSING_DATA_FLAG",
            "HOURS_TO_NEXT"
        ]
    ]
)

prepared_df = modeling_df.loc[
    modeling_df["TOTAL_CALLS"].notna()
    & modeling_df["NEXT_HOUR_CALLS"].notna()
    & (modeling_df["HOURS_TO_NEXT"] == 1)
].copy()

prepared_df["TOTAL_CALLS"] = prepared_df["TOTAL_CALLS"].astype(int)
prepared_df["NEXT_HOUR_CALLS"] = prepared_df["NEXT_HOUR_CALLS"].astype(int)

prepared_df = prepared_df.reset_index(drop=True)

print("\nPrepared modeling rows:", len(prepared_df))
print("Missing current counts:", prepared_df["TOTAL_CALLS"].isna().sum())
print("Missing targets:", prepared_df["NEXT_HOUR_CALLS"].isna().sum())
print(
    "Non-one-hour prediction gaps:",
    (prepared_df["HOURS_TO_NEXT"] != 1).sum()
)

print("\nPrepared dataset range:")
print("First prediction hour:", prepared_df["HOUR"].min())
print("Last prediction hour:", prepared_df["HOUR"].max())

display(prepared_df.head())

Rows excluded from modeling: 6

,HOUR,TOTAL_CALLS,NEXT_TIMESTAMP,NEXT_HOUR_CALLS,MISSING_DATA_FLAG,HOURS_TO_NEXT
1657,2024-03-10 01:00:00,55,2024-03-10 03:00:00,35,0,2.0
10392,2025-03-09 01:00:00,60,2025-03-09 03:00:00,33,0,2.0
19127,2026-03-08 01:00:00,40,2026-03-08 03:00:00,38,0,2.0
19344,2026-03-17 03:00:00,13,2026-03-17 04:00:00,<NA>,0,1.0
19345,2026-03-17 04:00:00,<NA>,2026-03-17 05:00:00,7,1,1.0
22076,2026-07-08 23:00:00,31,NaT,<NA>,0,NaN

Prepared modeling rows: 22071
Missing current counts: 0
Missing targets: 0
Non-one-hour prediction gaps: 0

Prepared dataset range:
First prediction hour: 2024-01-01 00:00:00
Last prediction hour: 2026-07-08 22:00:00

,HOUR,TOTAL_CALLS,MISSING_DATA_FLAG,NEXT_HOUR_CALLS,NEXT_TIMESTAMP,HOURS_TO_NEXT
0,2024-01-01 00:00:00,78,0,68,2024-01-01 01:00:00,1.0
1,2024-01-01 01:00:00,68,0,41,2024-01-01 02:00:00,1.0
2,2024-01-01 02:00:00,41,0,35,2024-01-01 03:00:00,1.0
3,2024-01-01 03:00:00,35,0,32,2024-01-01 04:00:00,1.0
4,2024-01-01 04:00:00,32,0,20,2024-01-01 05:00:00,1.0

In [15]:
import numpy as np

feature_df = prepared_df.copy()

target_time = feature_df["NEXT_TIMESTAMP"]

# Basic calendar features for the hour being predicted
feature_df["TARGET_HOUR"] = target_time.dt.hour
feature_df["TARGET_DAY_OF_WEEK"] = target_time.dt.dayofweek  # Monday=0
feature_df["TARGET_MONTH"] = target_time.dt.month
feature_df["TARGET_IS_WEEKEND"] = (
    feature_df["TARGET_DAY_OF_WEEK"] >= 5
).astype(int)

# Cyclical encodings
feature_df["HOUR_SIN"] = np.sin(
    2 * np.pi * feature_df["TARGET_HOUR"] / 24
)
feature_df["HOUR_COS"] = np.cos(
    2 * np.pi * feature_df["TARGET_HOUR"] / 24
)

feature_df["DAY_OF_WEEK_SIN"] = np.sin(
    2 * np.pi * feature_df["TARGET_DAY_OF_WEEK"] / 7
)
feature_df["DAY_OF_WEEK_COS"] = np.cos(
    2 * np.pi * feature_df["TARGET_DAY_OF_WEEK"] / 7
)

feature_df["MONTH_SIN"] = np.sin(
    2 * np.pi * (feature_df["TARGET_MONTH"] - 1) / 12
)
feature_df["MONTH_COS"] = np.cos(
    2 * np.pi * (feature_df["TARGET_MONTH"] - 1) / 12
)

calendar_columns = [
    "TARGET_HOUR",
    "TARGET_DAY_OF_WEEK",
    "TARGET_MONTH",
    "TARGET_IS_WEEKEND",
    "HOUR_SIN",
    "HOUR_COS",
    "DAY_OF_WEEK_SIN",
    "DAY_OF_WEEK_COS",
    "MONTH_SIN",
    "MONTH_COS"
]

print("Feature dataset shape:", feature_df.shape)
print(
    "Missing calendar-feature values:",
    feature_df[calendar_columns].isna().sum().sum()
)

print("\nCalendar feature ranges:")
display(feature_df[calendar_columns].agg(["min", "max"]))

print("\nFirst 10 calendar-feature examples:")
display(
    feature_df[
        [
            "HOUR",
            "NEXT_TIMESTAMP",
            "NEXT_HOUR_CALLS"
        ] + calendar_columns
    ].head(10)
)

Feature dataset shape: (22071, 16)
Missing calendar-feature values: 0

Calendar feature ranges:

,TARGET_HOUR,TARGET_DAY_OF_WEEK,TARGET_MONTH,TARGET_IS_WEEKEND,HOUR_SIN,HOUR_COS,DAY_OF_WEEK_SIN,DAY_OF_WEEK_COS,MONTH_SIN,MONTH_COS
min,0,0,1,0,-1.0,-1.0,-0.974928,-0.900969,-1.0,-1.0
max,23,6,12,1,1.0,1.0,0.974928,1.000000,1.0,1.0

First 10 calendar-feature examples:

,HOUR,NEXT_TIMESTAMP,NEXT_HOUR_CALLS,TARGET_HOUR,TARGET_DAY_OF_WEEK,TARGET_MONTH,TARGET_IS_WEEKEND,HOUR_SIN,HOUR_COS,DAY_OF_WEEK_SIN,DAY_OF_WEEK_COS,MONTH_SIN,MONTH_COS
0,2024-01-01 00:00:00,2024-01-01 01:00:00,68,1,0,1,0,0.258819,9.659258e-01,0.0,1.0,0.0,1.0
1,2024-01-01 01:00:00,2024-01-01 02:00:00,41,2,0,1,0,0.500000,8.660254e-01,0.0,1.0,0.0,1.0
2,2024-01-01 02:00:00,2024-01-01 03:00:00,35,3,0,1,0,0.707107,7.071068e-01,0.0,1.0,0.0,1.0
3,2024-01-01 03:00:00,2024-01-01 04:00:00,32,4,0,1,0,0.866025,5.000000e-01,0.0,1.0,0.0,1.0
4,2024-01-01 04:00:00,2024-01-01 05:00:00,20,5,0,1,0,0.965926,2.588190e-01,0.0,1.0,0.0,1.0
5,2024-01-01 05:00:00,2024-01-01 06:00:00,19,6,0,1,0,1.000000,6.123234e-17,0.0,1.0,0.0,1.0
6,2024-01-01 06:00:00,2024-01-01 07:00:00,16,7,0,1,0,0.965926,-2.588190e-01,0.0,1.0,0.0,1.0
7,2024-01-01 07:00:00,2024-01-01 08:00:00,17,8,0,1,0,0.866025,-5.000000e-01,0.0,1.0,0.0,1.0
8,2024-01-01 08:00:00,2024-01-01 09:00:00,21,9,0,1,0,0.707107,-7.071068e-01,0.0,1.0,0.0,1.0
9,2024-01-01 09:00:00,2024-01-01 10:00:00,21,10,0,1,0,0.500000,-8.660254e-01,0.0,1.0,0.0,1.0

In [16]:
# Lookup table containing call counts for each actual clock hour
call_count_lookup = (
    hourly_corrected_df
    .set_index("HOUR")["TOTAL_CALLS"]
)

# Lag times are measured relative to the predicted hour
lag_hours = [1, 2, 3, 24, 48, 168]

lag_columns = []

for lag in lag_hours:
    column_name = f"LAG_{lag}H"

    source_timestamp = (
        feature_df["NEXT_TIMESTAMP"]
        - pd.Timedelta(hours=lag)
    )

    feature_df[column_name] = source_timestamp.map(
        call_count_lookup
    )

    lag_columns.append(column_name)

print("Lag columns created:")
print(lag_columns)

print("\nMissing values by lag feature:")
print(feature_df[lag_columns].isna().sum())

print(
    "\nLAG_1H differs from current TOTAL_CALLS:",
    (
        feature_df["LAG_1H"]
        != feature_df["TOTAL_CALLS"]
    ).fillna(False).sum()
)

print("\nFirst 10 lag-feature examples:")
display(
    feature_df[
        [
            "HOUR",
            "TOTAL_CALLS",
            "NEXT_TIMESTAMP",
            "NEXT_HOUR_CALLS"
        ] + lag_columns
    ].head(10)
)

print("\nRows with any missing lag values:")
display(
    feature_df.loc[
        feature_df[lag_columns].isna().any(axis=1),
        [
            "HOUR",
            "NEXT_TIMESTAMP"
        ] + lag_columns
    ].head(20)
)

Lag columns created:
['LAG_1H', 'LAG_2H', 'LAG_3H', 'LAG_24H', 'LAG_48H', 'LAG_168H']

Missing values by lag feature:
LAG_1H        0
LAG_2H        5
LAG_3H        6
LAG_24H      27
LAG_48H      51
LAG_168H    171
dtype: int64

LAG_1H differs from current TOTAL_CALLS: 0

First 10 lag-feature examples:

,HOUR,TOTAL_CALLS,NEXT_TIMESTAMP,NEXT_HOUR_CALLS,LAG_1H,LAG_2H,LAG_3H,LAG_24H,LAG_48H,LAG_168H
0,2024-01-01 00:00:00,78,2024-01-01 01:00:00,68,78,<NA>,<NA>,<NA>,<NA>,<NA>
1,2024-01-01 01:00:00,68,2024-01-01 02:00:00,41,68,78,<NA>,<NA>,<NA>,<NA>
2,2024-01-01 02:00:00,41,2024-01-01 03:00:00,35,41,68,78,<NA>,<NA>,<NA>
3,2024-01-01 03:00:00,35,2024-01-01 04:00:00,32,35,41,68,<NA>,<NA>,<NA>
4,2024-01-01 04:00:00,32,2024-01-01 05:00:00,20,32,35,41,<NA>,<NA>,<NA>
5,2024-01-01 05:00:00,20,2024-01-01 06:00:00,19,20,32,35,<NA>,<NA>,<NA>
6,2024-01-01 06:00:00,19,2024-01-01 07:00:00,16,19,20,32,<NA>,<NA>,<NA>
7,2024-01-01 07:00:00,16,2024-01-01 08:00:00,17,16,19,20,<NA>,<NA>,<NA>
8,2024-01-01 08:00:00,17,2024-01-01 09:00:00,21,17,16,19,<NA>,<NA>,<NA>
9,2024-01-01 09:00:00,21,2024-01-01 10:00:00,21,21,17,16,<NA>,<NA>,<NA>

Rows with any missing lag values:

,HOUR,NEXT_TIMESTAMP,LAG_1H,LAG_2H,LAG_3H,LAG_24H,LAG_48H,LAG_168H
0,2024-01-01 00:00:00,2024-01-01 01:00:00,78,<NA>,<NA>,<NA>,<NA>,<NA>
1,2024-01-01 01:00:00,2024-01-01 02:00:00,68,78,<NA>,<NA>,<NA>,<NA>
2,2024-01-01 02:00:00,2024-01-01 03:00:00,41,68,78,<NA>,<NA>,<NA>
3,2024-01-01 03:00:00,2024-01-01 04:00:00,35,41,68,<NA>,<NA>,<NA>
4,2024-01-01 04:00:00,2024-01-01 05:00:00,32,35,41,<NA>,<NA>,<NA>
5,2024-01-01 05:00:00,2024-01-01 06:00:00,20,32,35,<NA>,<NA>,<NA>
6,2024-01-01 06:00:00,2024-01-01 07:00:00,19,20,32,<NA>,<NA>,<NA>
7,2024-01-01 07:00:00,2024-01-01 08:00:00,16,19,20,<NA>,<NA>,<NA>
8,2024-01-01 08:00:00,2024-01-01 09:00:00,17,16,19,<NA>,<NA>,<NA>
9,2024-01-01 09:00:00,2024-01-01 10:00:00,21,17,16,<NA>,<NA>,<NA>
10,2024-01-01 10:00:00,2024-01-01 11:00:00,21,21,17,<NA>,<NA>,<NA>
11,2024-01-01 11:00:00,2024-01-01 12:00:00,21,21,21,<NA>,<NA>,<NA>
12,2024-01-01 12:00:00,2024-01-01 13:00:00,27,21,21,<NA>,<NA>,<NA>
13,2024-01-01 13:00:00,2024-01-01 14:00:00,34,27,21,<NA>,<NA>,<NA>
14,2024-01-01 14:00:00,2024-01-01 15:00:00,26,34,27,<NA>,<NA>,<NA>
15,2024-01-01 15:00:00,2024-01-01 16:00:00,32,26,34,<NA>,<NA>,<NA>
16,2024-01-01 16:00:00,2024-01-01 17:00:00,30,32,26,<NA>,<NA>,<NA>
17,2024-01-01 17:00:00,2024-01-01 18:00:00,23,30,32,<NA>,<NA>,<NA>
18,2024-01-01 18:00:00,2024-01-01 19:00:00,32,23,30,<NA>,<NA>,<NA>
19,2024-01-01 19:00:00,2024-01-01 20:00:00,45,32,23,<NA>,<NA>,<NA>

In [17]:
# Build exact historical hourly values before each predicted timestamp
maximum_history = 168

history_lag_matrix = pd.DataFrame({
    lag: (
        feature_df["NEXT_TIMESTAMP"]
        - pd.Timedelta(hours=lag)
    ).map(call_count_lookup).astype("float64")
    for lag in range(1, maximum_history + 1)
})

rolling_windows = [3, 6, 24, 168]
rolling_columns = []

for window in rolling_windows:
    column_name = f"ROLLING_MEAN_{window}H"

    # Require every exact hour in the window to be available
    feature_df[column_name] = (
        history_lag_matrix
        .loc[:, 1:window]
        .mean(axis=1, skipna=False)
    )

    rolling_columns.append(column_name)

print("Rolling-average columns created:")
print(rolling_columns)

print("\nMissing values by rolling feature:")
print(feature_df[rolling_columns].isna().sum())

# Confirm that the 3-hour rolling mean uses only the three prior hours
complete_3h_mask = feature_df[
    ["LAG_1H", "LAG_2H", "LAG_3H"]
].notna().all(axis=1)

manual_3h_mean = (
    feature_df.loc[
        complete_3h_mask,
        ["LAG_1H", "LAG_2H", "LAG_3H"]
    ]
    .astype(float)
    .mean(axis=1)
)

maximum_difference = (
    feature_df.loc[
        complete_3h_mask,
        "ROLLING_MEAN_3H"
    ]
    - manual_3h_mean
).abs().max()

print(
    "\nMaximum difference in 3-hour validation:",
    maximum_difference
)

print("\nFirst 10 rolling-feature examples:")
display(
    feature_df[
        [
            "HOUR",
            "NEXT_TIMESTAMP",
            "NEXT_HOUR_CALLS"
        ]
        + lag_columns
        + rolling_columns
    ].head(10)
)

print("\nFirst rows with complete rolling features:")
display(
    feature_df.loc[
        feature_df[rolling_columns].notna().all(axis=1),
        [
            "HOUR",
            "NEXT_TIMESTAMP",
            "NEXT_HOUR_CALLS"
        ]
        + rolling_columns
    ].head(10)
)

Rolling-average columns created:
['ROLLING_MEAN_3H', 'ROLLING_MEAN_6H', 'ROLLING_MEAN_24H', 'ROLLING_MEAN_168H']

Missing values by rolling feature:
ROLLING_MEAN_3H       10
ROLLING_MEAN_6H       25
ROLLING_MEAN_24H     115
ROLLING_MEAN_168H    835
dtype: int64

Maximum difference in 3-hour validation: 0.0

First 10 rolling-feature examples:

,HOUR,NEXT_TIMESTAMP,NEXT_HOUR_CALLS,LAG_1H,LAG_2H,LAG_3H,LAG_24H,LAG_48H,LAG_168H,ROLLING_MEAN_3H,ROLLING_MEAN_6H,ROLLING_MEAN_24H,ROLLING_MEAN_168H
0,2024-01-01 00:00:00,2024-01-01 01:00:00,68,78,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
1,2024-01-01 01:00:00,2024-01-01 02:00:00,41,68,78,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN
2,2024-01-01 02:00:00,2024-01-01 03:00:00,35,41,68,78,<NA>,<NA>,<NA>,62.333333,NaN,NaN,NaN
3,2024-01-01 03:00:00,2024-01-01 04:00:00,32,35,41,68,<NA>,<NA>,<NA>,48.000000,NaN,NaN,NaN
4,2024-01-01 04:00:00,2024-01-01 05:00:00,20,32,35,41,<NA>,<NA>,<NA>,36.000000,NaN,NaN,NaN
5,2024-01-01 05:00:00,2024-01-01 06:00:00,19,20,32,35,<NA>,<NA>,<NA>,29.000000,45.666667,NaN,NaN
6,2024-01-01 06:00:00,2024-01-01 07:00:00,16,19,20,32,<NA>,<NA>,<NA>,23.666667,35.833333,NaN,NaN
7,2024-01-01 07:00:00,2024-01-01 08:00:00,17,16,19,20,<NA>,<NA>,<NA>,18.333333,27.166667,NaN,NaN
8,2024-01-01 08:00:00,2024-01-01 09:00:00,21,17,16,19,<NA>,<NA>,<NA>,17.333333,23.166667,NaN,NaN
9,2024-01-01 09:00:00,2024-01-01 10:00:00,21,21,17,16,<NA>,<NA>,<NA>,18.000000,20.833333,NaN,NaN

First rows with complete rolling features:

,HOUR,NEXT_TIMESTAMP,NEXT_HOUR_CALLS,ROLLING_MEAN_3H,ROLLING_MEAN_6H,ROLLING_MEAN_24H,ROLLING_MEAN_168H
167,2024-01-07 23:00:00,2024-01-08 00:00:00,34,33.000000,33.166667,27.083333,28.595238
168,2024-01-08 00:00:00,2024-01-08 01:00:00,21,34.666667,33.333333,26.833333,28.333333
169,2024-01-08 01:00:00,2024-01-08 02:00:00,19,30.333333,31.500000,26.541667,28.053571
170,2024-01-08 02:00:00,2024-01-08 03:00:00,12,24.666667,28.833333,26.333333,27.922619
171,2024-01-08 03:00:00,2024-01-08 04:00:00,16,17.333333,26.000000,26.416667,27.785714
172,2024-01-08 04:00:00,2024-01-08 05:00:00,8,15.666667,23.000000,26.166667,27.690476
173,2024-01-08 05:00:00,2024-01-08 06:00:00,8,12.000000,18.333333,26.000000,27.619048
174,2024-01-08 06:00:00,2024-01-08 07:00:00,29,10.666667,14.000000,25.666667,27.553571
175,2024-01-08 07:00:00,2024-01-08 08:00:00,34,15.000000,15.333333,26.166667,27.630952
176,2024-01-08 08:00:00,2024-01-08 09:00:00,38,23.666667,17.833333,26.708333,27.732143

In [18]:
print("Priority column data type:", combined_df["PRIORITY"].dtype)
print("Missing priority values:", combined_df["PRIORITY"].isna().sum())

print("\nUnique priority values:")
print(
    sorted(
        combined_df["PRIORITY"]
        .dropna()
        .unique()
        .tolist()
    )
)

print("\nOverall priority distribution:")
priority_distribution = (
    combined_df["PRIORITY"]
    .value_counts(dropna=False)
    .sort_index()
    .rename_axis("PRIORITY")
    .reset_index(name="CALL_COUNT")
)

priority_distribution["PERCENT"] = (
    priority_distribution["CALL_COUNT"]
    / len(combined_df)
    * 100
)

display(priority_distribution)

print("\nPriority distribution by source year:")
priority_by_year = pd.crosstab(
    combined_df["SOURCE_YEAR"],
    combined_df["PRIORITY"],
    dropna=False
)

display(priority_by_year)

print("\nSample records for each priority:")
priority_samples = (
    combined_df
    .sort_values("CALL_DATETIME")
    .groupby("PRIORITY", dropna=False)
    .head(3)
)

display(
    priority_samples[
        [
            "CALL_DATETIME",
            "CALL_NUMBER",
            "PRIORITY",
            "CALL_TYPE"
        ]
    ]
)

Priority column data type: int64
Missing priority values: 0

Unique priority values:
[1, 2, 3, 4, 5, 6, 8]

Overall priority distribution:

   PRIORITY  CALL_COUNT    PERCENT
0         1       20997   3.122792
1         2      199096  29.610681
2         3      248213  36.915638
3         4       77610  11.542597
4         5       45214   6.724481
5         6       81247  12.083512
6         8           2   0.000297

Priority distribution by source year:

PRIORITY        1      2      3      4      5      6  8
SOURCE_YEAR
2024         8892  84248  98131  31299  17772  32163  1
2025         8264  76730  97390  30554  17267  31890  0
2026         3841  38118  52692  15757  10175  17194  1

Sample records for each priority:

,CALL_DATETIME,CALL_NUMBER,PRIORITY,CALL_TYPE
0,2024-01-01 00:00:00,P240010001,3,"ALARM, AUDIBLE"
1,2024-01-01 00:00:43,P240010002,3,"DISTURBANCE, MUSIC"
2,2024-01-01 00:00:49,P240010003,3,SUSPICIOUS CIRCUMSTANCES
3,2024-01-01 00:01:17,P240010004,2,DISTURBANCE
4,2024-01-01 00:01:56,P240010005,4,"DISTURBANCE, FIRECRACKERS"
5,2024-01-01 00:01:58,P240010006,2,UNK TYPE 911 CALL
6,2024-01-01 00:02:16,P240010007,2,"DISTURBANCE, WEAPON"
9,2024-01-01 00:03:36,P240010011,4,"DISTURBANCE, MUSIC"
12,2024-01-01 00:05:43,P240010015,1,"ALARM, AUDIBLE"
14,2024-01-01 00:08:21,P240010017,4,"DISTURBANCE, FIRECRACKERS"
18,2024-01-01 00:10:33,P240010021,6,VEHICLE STOP
35,2024-01-01 00:23:30,P240010039,1,SUSPICIOUS CIRCUMSTANCES
53,2024-01-01 00:36:54,P240010058,6,VEHICLE STOP
54,2024-01-01 00:37:08,P240010059,6,VEHICLE STOP
108,2024-01-01 01:20:22,P240010118,1,MENTALLY DISTURBED PERSON
112,2024-01-01 01:27:41,P240010122,5,BATTERY
158,2024-01-01 02:17:24,P240010171,5,DISTURBANCE
186,2024-01-01 02:55:37,P240010202,5,SUSPICIOUS VEHICLE
99697,2024-05-17 07:29:50,P241380182,8,FIRE DEPARTMENT REQUEST FOR PD
654144,2026-06-14 08:46:12,P261650324,8,DISTURBANCE

In [19]:
# Group rare priority 8 into an OTHER category
priority_source = combined_df[
    ["HOUR", "PRIORITY"]
].copy()

priority_source["PRIORITY_GROUP"] = (
    priority_source["PRIORITY"]
    .where(
        priority_source["PRIORITY"].isin([1, 2, 3, 4, 5, 6]),
        "OTHER"
    )
    .astype(str)
)

# Count calls of each priority during each hour
hourly_priority_counts = (
    priority_source
    .groupby(["HOUR", "PRIORITY_GROUP"])
    .size()
    .unstack(fill_value=0)
)

required_priority_groups = ["1", "2", "3", "4", "5", "6", "OTHER"]

hourly_priority_counts = hourly_priority_counts.reindex(
    columns=required_priority_groups,
    fill_value=0
)

hourly_priority_counts.columns = [
    f"CURRENT_PRIORITY_{priority}_COUNT"
    for priority in required_priority_groups
]

priority_columns = hourly_priority_counts.columns.tolist()

# Join counts using the current prediction-origin hour
feature_df = feature_df.merge(
    hourly_priority_counts.reset_index(),
    on="HOUR",
    how="left",
    validate="many_to_one"
)

feature_df[priority_columns] = (
    feature_df[priority_columns]
    .fillna(0)
    .astype(int)
)

# Validate that priority counts equal the current hour's total calls
feature_df["PRIORITY_COUNT_SUM"] = (
    feature_df[priority_columns].sum(axis=1)
)

print("Priority features created:")
print(priority_columns)

print(
    "\nMissing priority-feature values:",
    feature_df[priority_columns].isna().sum().sum()
)

print(
    "Rows where priority counts do not equal TOTAL_CALLS:",
    (
        feature_df["PRIORITY_COUNT_SUM"]
        != feature_df["TOTAL_CALLS"]
    ).sum()
)

print("\nPriority-feature summary:")
display(feature_df[priority_columns].describe())

print("\nFirst 10 priority-feature examples:")
display(
    feature_df[
        [
            "HOUR",
            "TOTAL_CALLS",
            "NEXT_TIMESTAMP",
            "NEXT_HOUR_CALLS"
        ]
        + priority_columns
        + ["PRIORITY_COUNT_SUM"]
    ].head(10)
)

Priority features created:
['CURRENT_PRIORITY_1_COUNT', 'CURRENT_PRIORITY_2_COUNT', 'CURRENT_PRIORITY_3_COUNT', 'CURRENT_PRIORITY_4_COUNT', 'CURRENT_PRIORITY_5_COUNT', 'CURRENT_PRIORITY_6_COUNT', 'CURRENT_PRIORITY_OTHER_COUNT']

Missing priority-feature values: 0
Rows where priority counts do not equal TOTAL_CALLS: 0

Priority-feature summary:

,CURRENT_PRIORITY_1_COUNT,CURRENT_PRIORITY_2_COUNT,CURRENT_PRIORITY_3_COUNT,CURRENT_PRIORITY_4_COUNT,CURRENT_PRIORITY_5_COUNT,CURRENT_PRIORITY_6_COUNT,CURRENT_PRIORITY_OTHER_COUNT
count,22071.000000,22071.000000,22071.000000,22071.000000,22071.000000,22071.000000,22071.000000
mean,0.951112,9.018667,11.243940,3.515020,2.048435,3.678084,0.000091
std,1.054351,4.419128,4.964599,3.369233,2.053953,4.454206,0.009519
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,6.000000,8.000000,1.000000,0.000000,1.000000,0.000000
50%,1.000000,9.000000,11.000000,3.000000,2.000000,2.000000,0.000000
75%,1.000000,12.000000,14.000000,5.000000,3.000000,5.000000,0.000000
max,9.000000,44.000000,65.000000,55.000000,21.000000,64.000000,1.000000

First 10 priority-feature examples:

,HOUR,TOTAL_CALLS,NEXT_TIMESTAMP,NEXT_HOUR_CALLS,CURRENT_PRIORITY_1_COUNT,CURRENT_PRIORITY_2_COUNT,CURRENT_PRIORITY_3_COUNT,CURRENT_PRIORITY_4_COUNT,CURRENT_PRIORITY_5_COUNT,CURRENT_PRIORITY_6_COUNT,CURRENT_PRIORITY_OTHER_COUNT,PRIORITY_COUNT_SUM
0,2024-01-01 00:00:00,78,2024-01-01 01:00:00,68,2,23,18,30,0,5,0,78
1,2024-01-01 01:00:00,68,2024-01-01 02:00:00,41,3,28,9,22,1,5,0,68
2,2024-01-01 02:00:00,41,2024-01-01 03:00:00,35,2,21,6,10,2,0,0,41
3,2024-01-01 03:00:00,35,2024-01-01 04:00:00,32,1,18,7,7,0,2,0,35
4,2024-01-01 04:00:00,32,2024-01-01 05:00:00,20,1,8,12,10,0,1,0,32
5,2024-01-01 05:00:00,20,2024-01-01 06:00:00,19,0,7,8,5,0,0,0,20
6,2024-01-01 06:00:00,19,2024-01-01 07:00:00,16,0,9,7,3,0,0,0,19
7,2024-01-01 07:00:00,16,2024-01-01 08:00:00,17,0,4,6,5,1,0,0,16
8,2024-01-01 08:00:00,17,2024-01-01 09:00:00,21,0,10,4,2,1,0,0,17
9,2024-01-01 09:00:00,21,2024-01-01 10:00:00,21,0,3,15,2,0,1,0,21

In [20]:
split_df = feature_df.copy()

train_end = pd.Timestamp("2025-09-30 23:00:00")
validation_end = pd.Timestamp("2026-02-28 23:00:00")

split_df["SPLIT"] = np.select(
    [
        split_df["NEXT_TIMESTAMP"] <= train_end,
        (
            (split_df["NEXT_TIMESTAMP"] > train_end)
            & (split_df["NEXT_TIMESTAMP"] <= validation_end)
        ),
        split_df["NEXT_TIMESTAMP"] > validation_end
    ],
    [
        "train",
        "validation",
        "test"
    ],
    default="unassigned"
)

train_df = split_df.loc[
    split_df["SPLIT"] == "train"
].copy()

validation_df = split_df.loc[
    split_df["SPLIT"] == "validation"
].copy()

test_df = split_df.loc[
    split_df["SPLIT"] == "test"
].copy()

split_audit = (
    split_df
    .groupby("SPLIT")
    .agg(
        rows=("NEXT_HOUR_CALLS", "size"),
        prediction_start=("NEXT_TIMESTAMP", "min"),
        prediction_end=("NEXT_TIMESTAMP", "max")
    )
    .reset_index()
)

split_audit["percentage"] = (
    split_audit["rows"]
    / len(split_df)
    * 100
)

display(split_audit)

print("Total rows:", len(split_df))
print("Train rows:", len(train_df))
print("Validation rows:", len(validation_df))
print("Test rows:", len(test_df))

print(
    "\nUnassigned rows:",
    (split_df["SPLIT"] == "unassigned").sum()
)

print("\nChronological validation:")
print(
    "Train ends before validation begins:",
    train_df["NEXT_TIMESTAMP"].max()
    < validation_df["NEXT_TIMESTAMP"].min()
)

print(
    "Validation ends before test begins:",
    validation_df["NEXT_TIMESTAMP"].max()
    < test_df["NEXT_TIMESTAMP"].min()
)

print("\nBoundary rows:")
display(
    split_df.loc[
        split_df["NEXT_TIMESTAMP"].between(
            pd.Timestamp("2025-09-30 21:00:00"),
            pd.Timestamp("2025-10-01 02:00:00")
        ),
        [
            "HOUR",
            "NEXT_TIMESTAMP",
            "NEXT_HOUR_CALLS",
            "SPLIT"
        ]
    ]
)

display(
    split_df.loc[
        split_df["NEXT_TIMESTAMP"].between(
            pd.Timestamp("2026-02-28 21:00:00"),
            pd.Timestamp("2026-03-01 02:00:00")
        ),
        [
            "HOUR",
            "NEXT_TIMESTAMP",
            "NEXT_HOUR_CALLS",
            "SPLIT"
        ]
    ]
)

        SPLIT   rows    prediction_start      prediction_end  percentage
0        test   3116 2026-03-01 00:00:00 2026-07-08 23:00:00   14.118073
1       train  15331 2024-01-01 01:00:00 2025-09-30 23:00:00   69.462190
2  validation   3624 2025-10-01 00:00:00 2026-02-28 23:00:00   16.419736

Total rows: 22071
Train rows: 15331
Validation rows: 3624
Test rows: 3116

Unassigned rows: 0

Chronological validation:
Train ends before validation begins: True
Validation ends before test begins: True

Boundary rows:

                     HOUR      NEXT_TIMESTAMP  NEXT_HOUR_CALLS       SPLIT
15328 2025-09-30 20:00:00 2025-09-30 21:00:00               24       train
15329 2025-09-30 21:00:00 2025-09-30 22:00:00               35       train
15330 2025-09-30 22:00:00 2025-09-30 23:00:00               28       train
15331 2025-09-30 23:00:00 2025-10-01 00:00:00               29  validation
15332 2025-10-01 00:00:00 2025-10-01 01:00:00               17  validation
15333 2025-10-01 01:00:00 2025-10-01 02:00:00               17  validation

                     HOUR      NEXT_TIMESTAMP  NEXT_HOUR_CALLS       SPLIT
18952 2026-02-28 20:00:00 2026-02-28 21:00:00               57  validation
18953 2026-02-28 21:00:00 2026-02-28 22:00:00               62  validation
18954 2026-02-28 22:00:00 2026-02-28 23:00:00               57  validation
18955 2026-02-28 23:00:00 2026-03-01 00:00:00               45        test
18956 2026-03-01 00:00:00 2026-03-01 01:00:00               38        test
18957 2026-03-01 01:00:00 2026-03-01 02:00:00               31        test

In [21]:
# Keep only incident records belonging to training prediction-origin hours
training_hours = pd.Index(train_df["HOUR"].unique())

training_incidents = combined_df.loc[
    combined_df["HOUR"].isin(training_hours)
].copy()

# Create standardized call-type labels for inspection
raw_call_types = training_incidents["CALL_TYPE"].astype("string")

training_incidents["CALL_TYPE_CLEAN"] = (
    raw_call_types
    .str.strip()
    .str.upper()
    .replace("", pd.NA)
)

print("Training hourly rows:", len(train_df))
print("Training incident records:", len(training_incidents))
print(
    "Missing call types:",
    training_incidents["CALL_TYPE_CLEAN"].isna().sum()
)
print(
    "Unique cleaned call types:",
    training_incidents["CALL_TYPE_CLEAN"].nunique()
)

spacing_issues = (
    raw_call_types.fillna("")
    != raw_call_types.fillna("").str.strip()
).sum()

print("Labels with leading/trailing spaces:", spacing_issues)

# Frequency distribution based only on training data
call_type_distribution = (
    training_incidents["CALL_TYPE_CLEAN"]
    .value_counts(dropna=False)
    .rename_axis("CALL_TYPE_CLEAN")
    .reset_index(name="CALL_COUNT")
)

call_type_distribution["PERCENT"] = (
    call_type_distribution["CALL_COUNT"]
    / len(training_incidents)
    * 100
)

call_type_distribution["CUMULATIVE_PERCENT"] = (
    call_type_distribution["PERCENT"].cumsum()
)

print("\nTop 30 training call types:")
display(call_type_distribution.head(30))

# Compare the most common categories across training years
top_20_call_types = (
    call_type_distribution
    .dropna(subset=["CALL_TYPE_CLEAN"])
    .head(20)["CALL_TYPE_CLEAN"]
    .tolist()
)

call_type_by_year = pd.crosstab(
    training_incidents["SOURCE_YEAR"],
    training_incidents["CALL_TYPE_CLEAN"]
)

call_type_by_year = call_type_by_year.reindex(
    columns=top_20_call_types,
    fill_value=0
)

print("\nTop 20 call types by training year:")
display(call_type_by_year)

Training hourly rows: 15331
Training incident records: 471363
Missing call types: 0
Unique cleaned call types: 208
Labels with leading/trailing spaces: 0

Top 30 training call types:

,CALL_TYPE_CLEAN,CALL_COUNT,PERCENT,CUMULATIVE_PERCENT
0,VEHICLE STOP,47056,9.982964,9.982964
1,DISTURBANCE,44299,9.398065,19.381029
2,WELFARE CHECK,38875,8.247359,27.628388
3,"ALARM, AUDIBLE",34489,7.316866,34.945255
4,PARKING VIOLATION,20563,4.362455,39.30771
5,"DISTURBANCE, MUSIC",16330,3.464421,42.772131
6,"DISTURBANCE, FAMILY",14991,3.180351,45.952482
7,SUSPICIOUS PERSON,14668,3.111827,49.064309
8,TRESPASSING,13546,2.873794,51.938103
9,SUSPICIOUS VEHICLE,12817,2.719136,54.657239
10,STOLEN VEHICLE,12075,2.56172,57.218959
11,UNK TYPE 911 CALL,11622,2.465616,59.684574
12,SUSPICIOUS CIRCUMSTANCES,11619,2.464979,62.149554
13,THEFT,10779,2.286773,64.436326
14,RECKLESS DRIVING,9766,2.071864,66.50819
15,"VEHICLE ACCIDENT, PROPERTY DAMAGE",8494,1.802008,68.310198
16,PEDESTRIAN STOP,7189,1.525152,69.83535
17,TRAFFIC HAZARD,7097,1.505634,71.340983
18,MEET THE CITIZEN,7075,1.500966,72.84195
19,RECOVERED STOLEN VEHICLE,6136,1.301757,74.143707
20,WELFARE CHECK (COMBINED EVENT),5783,1.226868,75.370574
21,MISDEMEANOR HIT AND RUN,5474,1.161313,76.531887
22,FIRE DEPARTMENT REQUEST FOR PD,5083,1.078362,77.610249
23,BURGLARY REPORT (460),4607,0.977378,78.587628
24,BATTERY,4525,0.959982,79.54761
25,MALICIOUS MISCHIEF,4459,0.94598,80.49359
26,"ALARM, SILENT",4330,0.918613,81.412202
27,"DISTURBANCE, UNKNOWN",3431,0.727889,82.140092
28,BURGLARY (460),2817,0.597629,82.73772
29,VEHICLE BURGLARY,2710,0.574928,83.312649

Top 20 call types by training year:

CALL_TYPE_CLEAN,VEHICLE STOP,DISTURBANCE,WELFARE CHECK,"ALARM, AUDIBLE",PARKING VIOLATION,"DISTURBANCE, MUSIC","DISTURBANCE, FAMILY",SUSPICIOUS PERSON,TRESPASSING,SUSPICIOUS VEHICLE,STOLEN VEHICLE,UNK TYPE 911 CALL,SUSPICIOUS CIRCUMSTANCES,THEFT,RECKLESS DRIVING,"VEHICLE ACCIDENT, PROPERTY DAMAGE",PEDESTRIAN STOP,TRAFFIC HAZARD,MEET THE CITIZEN,RECOVERED STOLEN VEHICLE
SOURCE_YEAR,,,,,,,,,,,,,,,,,,,,
2024,26512,25438,22353,20753,12151,9671,8659,8342,7427,7469,7225,6971,6507,6243,5549,5007,3942,4302,3992,3691
2025,20544,18861,16522,13736,8412,6659,6332,6326,6119,5348,4850,4651,5112,4536,4217,3487,3247,2795,3083,2445

In [22]:
import re

# The top 20 categories were selected using training data only
selected_call_types = top_20_call_types.copy()

print("Selected training call types:")
for index, call_type in enumerate(selected_call_types, start=1):
    print(f"{index:2d}. {call_type}")

selected_coverage = (
    call_type_distribution
    .head(20)["PERCENT"]
    .sum()
)

print(
    "\nTraining-data coverage of selected call types:",
    round(selected_coverage, 2),
    "%"
)

# Clean call-type labels across the complete incident dataset
call_type_source = combined_df[
    ["HOUR", "CALL_TYPE"]
].copy()

call_type_source["CALL_TYPE_CLEAN"] = (
    call_type_source["CALL_TYPE"]
    .astype("string")
    .str.strip()
    .str.upper()
    .replace("", pd.NA)
)

# Preserve the selected training categories and group everything else
call_type_source["CALL_TYPE_GROUP"] = (
    call_type_source["CALL_TYPE_CLEAN"]
    .where(
        call_type_source["CALL_TYPE_CLEAN"].isin(
            selected_call_types
        ),
        "OTHER"
    )
    .fillna("OTHER")
)

# Count each call-type group during every current hour
hourly_call_type_counts = (
    call_type_source
    .groupby(["HOUR", "CALL_TYPE_GROUP"])
    .size()
    .unstack(fill_value=0)
)

required_call_type_groups = (
    selected_call_types + ["OTHER"]
)

hourly_call_type_counts = (
    hourly_call_type_counts
    .reindex(
        columns=required_call_type_groups,
        fill_value=0
    )
)

# Create safe machine-learning column names
call_type_name_map = {}

for call_type in required_call_type_groups:
    safe_name = re.sub(
        r"[^A-Z0-9]+",
        "_",
        call_type
    ).strip("_")

    call_type_name_map[call_type] = (
        f"CURRENT_CALLTYPE_{safe_name}_COUNT"
    )

hourly_call_type_counts = (
    hourly_call_type_counts
    .rename(columns=call_type_name_map)
)

call_type_columns = (
    hourly_call_type_counts.columns.tolist()
)

# Join using the current hour, not the predicted hour
feature_df = feature_df.merge(
    hourly_call_type_counts.reset_index(),
    on="HOUR",
    how="left",
    validate="many_to_one"
)

feature_df[call_type_columns] = (
    feature_df[call_type_columns]
    .fillna(0)
    .astype(int)
)

# Validate that every incident belongs to exactly one category
feature_df["CALL_TYPE_COUNT_SUM"] = (
    feature_df[call_type_columns]
    .sum(axis=1)
)

print("\nNumber of call-type features:", len(call_type_columns))

print(
    "Missing call-type feature values:",
    feature_df[call_type_columns]
    .isna()
    .sum()
    .sum()
)

print(
    "Rows where call-type counts do not equal TOTAL_CALLS:",
    (
        feature_df["CALL_TYPE_COUNT_SUM"]
        != feature_df["TOTAL_CALLS"]
    ).sum()
)

print("\nFirst 10 call-type feature examples:")
display(
    feature_df[
        [
            "HOUR",
            "TOTAL_CALLS",
            "NEXT_TIMESTAMP",
            "NEXT_HOUR_CALLS"
        ]
        + call_type_columns
        + ["CALL_TYPE_COUNT_SUM"]
    ].head(10)
)

Selected training call types:
 1. VEHICLE STOP
 2. DISTURBANCE
 3. WELFARE CHECK
 4. ALARM, AUDIBLE
 5. PARKING VIOLATION
 6. DISTURBANCE, MUSIC
 7. DISTURBANCE, FAMILY
 8. SUSPICIOUS PERSON
 9. TRESPASSING
10. SUSPICIOUS VEHICLE
11. STOLEN VEHICLE
12. UNK TYPE 911 CALL
13. SUSPICIOUS CIRCUMSTANCES
14. THEFT
15. RECKLESS DRIVING
16. VEHICLE ACCIDENT, PROPERTY DAMAGE
17. PEDESTRIAN STOP
18. TRAFFIC HAZARD
19. MEET THE CITIZEN
20. RECOVERED STOLEN VEHICLE

Training-data coverage of selected call types: 74.14 %

Number of call-type features: 21
Missing call-type feature values: 0
Rows where call-type counts do not equal TOTAL_CALLS: 0

First 10 call-type feature examples:

,HOUR,TOTAL_CALLS,NEXT_TIMESTAMP,NEXT_HOUR_CALLS,CURRENT_CALLTYPE_VEHICLE_STOP_COUNT,CURRENT_CALLTYPE_DISTURBANCE_COUNT,CURRENT_CALLTYPE_WELFARE_CHECK_COUNT,CURRENT_CALLTYPE_ALARM_AUDIBLE_COUNT,CURRENT_CALLTYPE_PARKING_VIOLATION_COUNT,CURRENT_CALLTYPE_DISTURBANCE_MUSIC_COUNT,...,CURRENT_CALLTYPE_SUSPICIOUS_CIRCUMSTANCES_COUNT,CURRENT_CALLTYPE_THEFT_COUNT,CURRENT_CALLTYPE_RECKLESS_DRIVING_COUNT,CURRENT_CALLTYPE_VEHICLE_ACCIDENT_PROPERTY_DAMAGE_COUNT,CURRENT_CALLTYPE_PEDESTRIAN_STOP_COUNT,CURRENT_CALLTYPE_TRAFFIC_HAZARD_COUNT,CURRENT_CALLTYPE_MEET_THE_CITIZEN_COUNT,CURRENT_CALLTYPE_RECOVERED_STOLEN_VEHICLE_COUNT,CURRENT_CALLTYPE_OTHER_COUNT,CALL_TYPE_COUNT_SUM
0,2024-01-01 00:00:00,78,2024-01-01 01:00:00,68,5,6,0,7,0,16,...,2,0,3,0,0,0,0,0,32,78
1,2024-01-01 01:00:00,68,2024-01-01 02:00:00,41,5,9,3,1,1,19,...,4,0,1,0,0,0,0,0,15,68
2,2024-01-01 02:00:00,41,2024-01-01 03:00:00,35,0,7,4,2,0,10,...,0,0,1,0,0,0,0,0,8,41
3,2024-01-01 03:00:00,35,2024-01-01 04:00:00,32,2,5,3,2,0,6,...,0,0,0,1,0,0,0,0,9,35
4,2024-01-01 04:00:00,32,2024-01-01 05:00:00,20,1,4,0,5,2,8,...,0,0,1,0,0,0,0,0,5,32
5,2024-01-01 05:00:00,20,2024-01-01 06:00:00,19,0,1,0,3,0,5,...,1,0,2,0,0,0,0,0,5,20
6,2024-01-01 06:00:00,19,2024-01-01 07:00:00,16,0,5,4,2,1,1,...,0,0,0,0,0,0,0,0,2,19
7,2024-01-01 07:00:00,16,2024-01-01 08:00:00,17,0,1,1,1,1,1,...,1,0,0,0,0,0,0,2,4,16
8,2024-01-01 08:00:00,17,2024-01-01 09:00:00,21,0,1,2,1,1,1,...,1,0,0,0,0,0,0,0,5,17
9,2024-01-01 09:00:00,21,2024-01-01 10:00:00,21,1,2,1,3,2,0,...,0,1,0,0,0,2,0,1,5,21

In [23]:
# Require all lag and rolling-history features to be available
history_feature_columns = lag_columns + rolling_columns

complete_history_mask = (
    feature_df[history_feature_columns]
    .notna()
    .all(axis=1)
)

final_feature_df = (
    feature_df.loc[complete_history_mask]
    .copy()
    .reset_index(drop=True)
)

# Recreate the chronological split because feature_df was updated
final_feature_df["SPLIT"] = np.select(
    [
        final_feature_df["NEXT_TIMESTAMP"] <= train_end,
        (
            (final_feature_df["NEXT_TIMESTAMP"] > train_end)
            & (final_feature_df["NEXT_TIMESTAMP"] <= validation_end)
        ),
        final_feature_df["NEXT_TIMESTAMP"] > validation_end
    ],
    [
        "train",
        "validation",
        "test"
    ],
    default="unassigned"
)

final_train_df = final_feature_df.loc[
    final_feature_df["SPLIT"] == "train"
].copy()

final_validation_df = final_feature_df.loc[
    final_feature_df["SPLIT"] == "validation"
].copy()

final_test_df = final_feature_df.loc[
    final_feature_df["SPLIT"] == "test"
].copy()

print("Rows before history filtering:", len(feature_df))
print(
    "Rows removed for incomplete history:",
    (~complete_history_mask).sum()
)
print("Final complete-history rows:", len(final_feature_df))

print("\nMissing values in history features:")
print(
    final_feature_df[history_feature_columns]
    .isna()
    .sum()
    .sum()
)

final_split_audit = (
    final_feature_df
    .groupby("SPLIT")
    .agg(
        rows=("NEXT_HOUR_CALLS", "size"),
        prediction_start=("NEXT_TIMESTAMP", "min"),
        prediction_end=("NEXT_TIMESTAMP", "max")
    )
    .reset_index()
)

final_split_audit["percentage"] = (
    final_split_audit["rows"]
    / len(final_feature_df)
    * 100
)

print("\nFinal split audit:")
display(final_split_audit)

print("\nChronological checks:")
print(
    "Train before validation:",
    final_train_df["NEXT_TIMESTAMP"].max()
    < final_validation_df["NEXT_TIMESTAMP"].min()
)

print(
    "Validation before test:",
    final_validation_df["NEXT_TIMESTAMP"].max()
    < final_test_df["NEXT_TIMESTAMP"].min()
)

print(
    "Unassigned rows:",
    (final_feature_df["SPLIT"] == "unassigned").sum()
)

Rows before history filtering: 22071
Rows removed for incomplete history: 835
Final complete-history rows: 21236

Missing values in history features:
0

Final split audit:

        SPLIT   rows prediction_start      prediction_end  percentage
0        test   2782       2026-03-01 2026-07-08 23:00:00   13.100396
1       train  14830       2024-01-08 2025-09-30 23:00:00   69.834244
2  validation   3624       2025-10-01 2026-02-28 23:00:00   17.065361

Chronological checks:
Train before validation: True
Validation before test: True
Unassigned rows: 0

In [24]:
# Combine all leakage-safe candidate features
candidate_feature_columns = (
    calendar_columns
    + lag_columns
    + rolling_columns
    + priority_columns
    + call_type_columns
)

# Remove any accidental duplicate column names while preserving order
candidate_feature_columns = list(
    dict.fromkeys(candidate_feature_columns)
)

model_ready_df = final_feature_df[
    [
        "HOUR",
        "NEXT_TIMESTAMP",
        "SPLIT"
    ]
    + candidate_feature_columns
    + ["NEXT_HOUR_CALLS"]
].copy()

# Convert the feature matrix to numeric values for validation
numeric_feature_matrix = (
    model_ready_df[candidate_feature_columns]
    .apply(pd.to_numeric, errors="coerce")
)

future_or_target_columns = [
    column
    for column in candidate_feature_columns
    if column in {
        "NEXT_HOUR_CALLS",
        "NEXT_TIMESTAMP",
        "HOUR",
        "SPLIT"
    }
    or column.startswith("NEXT_")
]

constant_features = [
    column
    for column in candidate_feature_columns
    if numeric_feature_matrix[column].nunique(dropna=False) <= 1
]

print("Model-ready rows:", len(model_ready_df))
print("Candidate feature count:", len(candidate_feature_columns))

print(
    "Duplicate feature names:",
    len(candidate_feature_columns)
    - len(set(candidate_feature_columns))
)

print(
    "Non-numeric values after conversion:",
    numeric_feature_matrix.isna().sum().sum()
)

print(
    "Infinite feature values:",
    np.isinf(
        numeric_feature_matrix.to_numpy(dtype=float)
    ).sum()
)

print(
    "Target or future columns incorrectly included:",
    future_or_target_columns
)

print("Constant features:", constant_features)

print("\nRows by split:")
print(model_ready_df["SPLIT"].value_counts())

print("\nTarget summary by split:")
display(
    model_ready_df
    .groupby("SPLIT")["NEXT_HOUR_CALLS"]
    .describe()
)

print("\nFirst five model-ready rows:")
display(model_ready_df.head())

Model-ready rows: 21236
Candidate feature count: 48
Duplicate feature names: 0
Non-numeric values after conversion: 0
Infinite feature values: 0
Target or future columns incorrectly included: []
Constant features: []

Rows by split:
SPLIT
train         14830
validation     3624
test           2782
Name: count, dtype: int64

Target summary by split:

              count       mean        std  min   25%   50%   75%    max
SPLIT
test         2782.0  31.815960  15.150068  4.0  22.0  31.0  39.0  166.0
train       14830.0  30.775118  12.137236  2.0  22.0  31.0  38.0  101.0
validation   3624.0  28.197296  11.155167  2.0  20.0  29.0  36.0   79.0

First five model-ready rows:

,HOUR,NEXT_TIMESTAMP,SPLIT,TARGET_HOUR,TARGET_DAY_OF_WEEK,TARGET_MONTH,TARGET_IS_WEEKEND,HOUR_SIN,HOUR_COS,DAY_OF_WEEK_SIN,...,CURRENT_CALLTYPE_SUSPICIOUS_CIRCUMSTANCES_COUNT,CURRENT_CALLTYPE_THEFT_COUNT,CURRENT_CALLTYPE_RECKLESS_DRIVING_COUNT,CURRENT_CALLTYPE_VEHICLE_ACCIDENT_PROPERTY_DAMAGE_COUNT,CURRENT_CALLTYPE_PEDESTRIAN_STOP_COUNT,CURRENT_CALLTYPE_TRAFFIC_HAZARD_COUNT,CURRENT_CALLTYPE_MEET_THE_CITIZEN_COUNT,CURRENT_CALLTYPE_RECOVERED_STOLEN_VEHICLE_COUNT,CURRENT_CALLTYPE_OTHER_COUNT,NEXT_HOUR_CALLS
0,2024-01-07 23:00:00,2024-01-08 00:00:00,train,0,0,1,0,0.000000,1.000000,0.0,...,0,0,1,1,1,0,0,2,4,34
1,2024-01-08 00:00:00,2024-01-08 01:00:00,train,1,0,1,0,0.258819,0.965926,0.0,...,0,0,2,0,1,0,0,0,5,21
2,2024-01-08 01:00:00,2024-01-08 02:00:00,train,2,0,1,0,0.500000,0.866025,0.0,...,0,0,1,0,1,0,0,0,2,19
3,2024-01-08 02:00:00,2024-01-08 03:00:00,train,3,0,1,0,0.707107,0.707107,0.0,...,0,0,0,0,0,1,0,2,5,12
4,2024-01-08 03:00:00,2024-01-08 04:00:00,train,4,0,1,0,0.866025,0.500000,0.0,...,1,0,0,0,1,0,0,0,2,16

In [25]:
import json
import os

processed_folder = (
    "/content/drive/MyDrive/"
    "CS171_Police_Call_Project/data_processed"
)

os.makedirs(processed_folder, exist_ok=True)

model_ready_path = os.path.join(
    processed_folder,
    "model_ready_hourly.csv"
)

feature_list_path = os.path.join(
    processed_folder,
    "candidate_features.json"
)

split_audit_path = os.path.join(
    processed_folder,
    "final_split_audit.csv"
)

# Save the complete model-ready dataset
model_ready_df.to_csv(
    model_ready_path,
    index=False
)

# Save the exact feature-column list
with open(feature_list_path, "w") as file:
    json.dump(
        candidate_feature_columns,
        file,
        indent=2
    )

# Save the final split summary
final_split_audit.to_csv(
    split_audit_path,
    index=False
)

print("Saved files:")

for path in [
    model_ready_path,
    feature_list_path,
    split_audit_path
]:
    print(
        os.path.basename(path),
        "- exists:",
        os.path.exists(path),
        "- size:",
        os.path.getsize(path),
        "bytes"
    )

# Reload the main file to verify it
saved_model_ready_df = pd.read_csv(
    model_ready_path,
    parse_dates=["HOUR", "NEXT_TIMESTAMP"]
)

print("\nReloaded dataset shape:", saved_model_ready_df.shape)
print(
    "Matches original shape:",
    saved_model_ready_df.shape == model_ready_df.shape
)

print(
    "Reloaded split counts:"
)
print(saved_model_ready_df["SPLIT"].value_counts())

Saved files:
model_ready_hourly.csv - exists: True - size: 6371641 bytes
candidate_features.json - exists: True - size: 1499 bytes
final_split_audit.csv - exists: True - size: 240 bytes

Reloaded dataset shape: (21236, 52)
Matches original shape: True
Reloaded split counts:
SPLIT
train         14830
validation     3624
test           2782
Name: count, dtype: int64